kind: pipeline
name: default

steps:
- name: node-build-frontend
  image: node:19-alpine
  settings:
    repo: kinnairdclan/youtube-dl-web
  commands:
    - apk add --update yarn
    - cd ./frontend && yarn install --quiet; yarn build --quiet
    - cd .. && cp -rv ./frontend ./nginx/

- name: build-server
  image: plugins/docker
  settings:
    context: ./server
    dockerfile : ./server/Dockerfile
    repo: kinnairdclan/youtube-dl-web-server
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_access_token

- name: build-nginx
  image: plugins/docker
  context: ./nginx
  settings:
    context: ./nginx
    dockerfile: ./nginx/Dockerfile.nossl
    repo: kinnairdclan/youtube-dl-web-nginx
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_access_token
