name: Build with Docker Compose
run-name: "${{ github.event_name }}: ${{ github.ref_name }}: ${{ github.event.head_commit.message }}"
on:
  push:
    branches:
      - "master"
  pull_request:
    types: [opened, reopened]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Change ownership to 1000:1000
        run: sudo chown -R 1000:1000 .
      - name: Build Frontend
        working-directory: ./frontend
        run: |
          bash ./build.sh
      - run: docker-compose build